com.sparc.wc.product.SPARCTechPackShare.username=flexplm-sharefile-tester@sparcgroup.com
com.sparc.wc.product.SPARCTechPackShare.password=b2kyZyBtcmx3IG51MnQgc3pzdg0KIA==
com.sparc.wc.product.SPARCTechPackShare.hostname=sparcgroup.sharefile.com
com.sparc.wc.product.SPARCTechPackShare.clientId=K0GSDXTk49q7AHSHKcCOpOOJ76LmlpBR
com.sparc.wc.product.SPARCTechPackShare.clientSecret=3ITfwg7tpI1lUfPokFgGBJle4iG91OD8zcmL8zHqwOp9qhOR