#Build Property File
#Tue, 01 Apr 2025 16:31:29 +0000
##############################################################################
#
# build.properties
# This file is the reference ant build file
#    Refer to ./ant/release.properties for Release details
#
##############################################################################

## Provide a Component Name (Used during compilation to name the Jar file)
component.name=Galaxy

## Site Admin Name [ default is "wcadmin" (Alternate name Administrator does not exist anymore with Windchill 12) ]
wcadmin.username=wcadmin

#-----------------
# Select the Installation Type:
#  Normal Installation Types:
#    installation.type=1  - All          [Copy Files, Compile, Restart Server, Load Files]" />
#    installation.type=2  - Load Only    [Copy Files, Load Files] (No Compile, No Restart Server)" />
#    installation.type=3  - Copy Only    [Copy Files] (No Compile, No Restart Server, No Load Files)" />
#    installation.type=4  - Deploy Only  [Copy Files, Compile, Restart Server] (No Load Files)" />
#  Extra Installation Types:
#    installation.type=5  - Print Package Content" />
#    installation.type=6  - Abort (Quit)" />
#    installation.type=99 - Equivalent to No Installation Type set
#-----------------
installation.type=1

# Manage Environment Type Parameters
#  Following Properties are used to help determine the Environment Type
#
#   The installation parameter "environment.type" will be calculated based on the "wt.rmi.server.hostname" 
#   The mapping will have to be setup as part of the Build delivery
#     The Values DEV/TEST/QA/PROD hereafter are samples, they can be fullfilled with any string values.
#   These Values can then be used on build.xml with the property ${environment.type}
#     It should help deploying either one or other environment specific configuration.

galaxy-test1.ptcmscloud.com=TEST
galaxy-dev1.ptcmscloud.com=DEV
galaxy-qa2.ptcmscloud.com=QA
galaxy.ptcmscloud.com=PROD

# Provide Organization Name
#  Can be used as variable ${org.name} on build.xml
org.name=galaxy
com.lcs.wc.util.flexContainer.organizationName=galaxy
com.lcs.wc.util.flexContainer.libraryName=FlexPLM

## WaitForWindchill Automatically during installation [ default is true ]
# waitforwindchill.auto=false

## Provide the version being installed (Used for logging purpose or if register.component=true)
version=1.0.0.0.16
install.sequence=01
windchill.datecode=12.0.3.13
windchill.releasenumber=12.0
component.displayname=SCF Build V${version}
## Uncomment next line to activate component registration [ default is false ]
register.component=true

## Compile Java classes using a custom encoding [ default is UTF-8 ]
# classEncoding=cp1252

## Compile Java classes using a runtime.classpath as defined on tools.xml [ default is false ]
# use.runtime.classpath=true

## Enforce executing MakeJar after Java and RbInfo Compilation [ Only for Release greated than 12.X ]
#   [ default value is false for windchill Release greater or equals to 12.X ]
# force.makejar=true

## Provide the separator used on delivery note [ default is "," ]
# csv.sep=;

## Do not reload files already successfully loaded into Windchill [ default is false ]
# skip.already.loaded.files=true

## Auto Execute Load of Delete SoftType files generated on ${wt.temp}/LWCTypeImpExp folder during SoftType Import [ default is false ]
# lwctypeimpexp.autodeletetypes=true

## Auto Execute Load of Delete Attributes files generated on ${wt.temp}/LWCTypeImpExp folder during SoftType Import [ default is false ]
# lwctypeimpexp.autodeleteattributes=true

## Define a custom buildhistory folder to register succeeded loadFile History [ default is ${wt.home}/buildhistory ]
# builds.history.dir=/appl/ptc/builds/buildhistory

## Surround the Load File execution by disabling/enabling the property com.ptc.core.lwc.PrimeTypeCache [ default is false ]
# auto.disable.prime.type.cache=true


#####################

## Provide the name of the Unix User executing installation [ default is "wtadmin" ]
## Only set this variable if the linux user used for installation is not "wtadmin"
# installation.unix.user=wcadmin

## wt.home property is the path to WT_HOME [ default is env.WT_HOME ]
## Only set this variable if env.WT_HOME is not set
# wt.home=/appl/ptc/Windchill_11.0/Windchill
# wt.home=C:\PTC\Windchill_12.0\Windchill

# Shared folder to create build remotely on Team City 
#LOCAL_HOME=/appl/ptc/Windchill_12.0/Windchill
#LOCAL_HOME=C:\PTC\Windchill_12.0\Windchill

## Provide the version of the TempPatch being installed (Used for logging purpose or if register.temppatch=true)
## Uncomment the lines and Replace X and N with Correct values to enable
# tp.name=11.X-M0N0_CPSXBN
# tp.sequence=0N
# Default Folder on which to deliver TempPatch in a SCF Package
# tempPatch.dir=temppatch
## Uncomment next line to activate component registration [ default is false ]
# register.temppatch=true

## Provide a specific Installation BaseDir [ default is same as build.xml folder location ]
# By providing a specific path, install logs, archives and delivery notes will be generated on this specific location.
# installer.basedir=/tmp/SIC.1.2.2.3
