## Property Entries needed in the BOM Price Conversion Customization
## Add column utility entry start
Master=com.lcs.wc.calendar.LCSCalendar,com.lcs.wc.calendar.LCSCalendarTask,com.lcs.wc.change.LCSChangeActivity,com.lcs.wc.color.LCSColor,com.lcs.wc.color.LCSPalette,com.lcs.wc.color.LCSPaletteMaterialColorLink,com.lcs.wc.color.LCSPaletteMaterialLink,com.lcs.wc.color.LCSPaletteToColorLink,com.lcs.wc.construction.LCSConstructionDetail,com.lcs.wc.construction.LCSConstructionInfo,com.lcs.wc.country.LCSCountry,com.lcs.wc.document.LCSDocument,com.lcs.wc.document.LCSDocumentCollection,com.lcs.wc.document.LCSImage,com.lcs.wc.epmstruct.FlexEPMDocToSpecLink,com.lcs.wc.flexbom.FlexBOMPart,com.lcs.wc.flexbom.FlexBOMLink,com.lcs.wc.foundation.EffectivityContext,com.lcs.wc.foundation.LCSLifecycleManaged,com.lcs.wc.foundation.LCSLogEntry,com.lcs.wc.foundation.LCSRevisableEntity,com.lcs.wc.last.LCSLast,com.lcs.wc.material.LCSMaterial,com.lcs.wc.material.LCSMaterialColor,com.lcs.wc.material.LCSMaterialSupplier,com.lcs.wc.material.MaterialPricingEntry,com.lcs.wc.measurements.LCSMeasurements,com.lcs.wc.measurements.LCSPointsOfMeasure,com.lcs.wc.media.LCSMedia,com.lcs.wc.moa.LCSMOAObject,com.lcs.wc.partstruct.FlexPartToSpecLink,com.lcs.wc.placeholder.Placeholder,com.lcs.wc.planning.FlexPlan,com.lcs.wc.planning.PlanLineItem,com.lcs.wc.product.LCSProduct,com.lcs.wc.product.LCSSKU,com.lcs.wc.product.ProductDestination,com.lcs.wc.sample.LCSSample,com.lcs.wc.sample.LCSSampleRequest,com.lcs.wc.season.LCSProductSeasonLink,com.lcs.wc.season.LCSSKUSeasonLink,com.lcs.wc.season.LCSSeason,com.lcs.wc.season.SeasonGroup,com.lcs.wc.season.SeasonGroupToSKULink,com.lcs.wc.season.SeasonGroupToProductLink,com.lcs.wc.sizing.ProdSizeCategoryToSeason,com.lcs.wc.sizing.ProductSizeCategory,com.lcs.wc.skusize.SKUSize,com.lcs.wc.skusize.SKUSizeSource,com.lcs.wc.skusize.SKUSizeToSeason,com.lcs.wc.sourcing.LCSProductCostSheet,com.lcs.wc.sourcing.LCSSKUCostSheet,com.lcs.wc.sourcing.LCSSKUSourcingLink,com.lcs.wc.sourcing.LCSSourceToSeasonLink,com.lcs.wc.sourcing.LCSSourcingConfig,com.lcs.wc.sourcing.OrderConfirmation,com.lcs.wc.sourcing.OrderConfirmationLineItem,com.lcs.wc.sourcing.RFQRequest,com.lcs.wc.sourcing.RFQResponse,com.lcs.wc.sourcing.RFQToQuotableLink,com.lcs.wc.specification.FlexSpecification,com.lcs.wc.supplier.LCSSupplier,com.lcs.wc.testing.TestCondition,com.lcs.wc.testing.TestDetails,com.lcs.wc.testing.TestMethod,com.lcs.wc.testing.TestProperty,com.lcs.wc.testing.TestSpecification
## Add column utility entry end
com.sparc.wc.util.SPARCFetchReusableTableData.PURCHASE_UOM_MATERIALSUPPLIER_KEY=scPurchaseUOM
com.sparc.wc.util.SPARCFetchReusableTableData.BOM_UOM_MATERIALSUPPLIER_KEY=scBOMUOM
com.sparc.wc.util.SPARCFetchReusableTableData.MOA_DELIMITER=~
com.sparc.wc.util.SPARCFetchReusableTableData.SPARC_BOM_PRICE_CONVERSION_MOATABLE_ATTKEY=scBOMPriceConversion
com.sparc.wc.util.SPARCFetchReusableTableData.SPARC_BOM_PRICE_CONVERSION_BUSINESSOBJECT_FULL_PATH=Business Object\\scBOMPriceConversionControl
com.sparc.wc.util.SPARCFetchReusableTableData.SPARC_MOA_PURCHASEUOM_KEY=scPurchaseUOMMS
com.sparc.wc.util.SPARCFetchReusableTableData.SPARC_MOA_BOMUOM_KEY=scBOMUOMMS
com.sparc.wc.util.SPARCFetchReusableTableData.SPARC_MOA_CONVERSIONFACTOR_KEY=scBOMPriceConversionFactor
com.sparc.wc.util.SPARCFetchReusableTableData.SPARC_MOA_FOBSTRING_CONVERSIONFACTOR=SCBOMPRICECONVERSIONFACTOR
com.sparc.wc.material.BOMPriceCalculations.PURCHASE_UOM=scPurchaseUOM
com.sparc.wc.material.BOMPriceCalculations.BOM_UOM=scBOMUOM
com.sparc.wc.material.BOMPriceCalculations.MOA_DELIMITER=~
com.sparc.wc.material.BOMPriceCalculations.SPARC_MPE_FOBSTRING=
com.sparc.wc.material.BOMPriceCalculations.SPARC_MPE_UNITPRICEKEY=scUnitPriceMaterialPricingObject	
com.sparc.wc.material.BOMPriceCalculations.SPARC_MPE_BULKPRICEKEY=scBulkPriceMaterialPricingObject
com.sparc.wc.material.BOMPriceCalculations.SPARC_MPE_BOMPRICE=pricingEntryPrice
com.sparc.wc.material.BOMPriceCalculations.SPARC_MATSUPP_UNITPRICEKEY = scUnitPrice
com.sparc.wc.material.BOMPriceCalculations.SPARC_MATSUPP_BOMPRICE = materialPrice
com.sparc.wc.material.MATERIAL_PRICING_CLASSNAME_OR =OR:com.lcs.wc.material.MaterialPricingEntry:
com.sparc.wc.material.BOMPriceCalculations.BUSINESSOBJECTIDA2A2=LCSLIFECYCLEMANAGED.IDA2A2
com.sparc.wc.material.BOMPriceCalculations.BUSINESSOBJECT_CLASSNAME_OR=OR:com.lcs.wc.foundation.LCSLifecycleManaged:


## Integration start
Integration.attributes.ProductSecondaryKeys=scBrand,scGender,scAge,sclining,scinlaysole,scupper,scoutsoledescription,scfitsilhoette,scproductwidth,scbrandassetpartner,sctechnology,scbenefits,scfeatures,scSizeRange
Integration.attributes.ProductSeasonSecondaryKeys=scDivision,scProductGroup,scProductType,scsportcategory,sccorpmarketingline,sccatmarketingline,scsalesline,sctechnologyconcept,scsustainabilityethics,scFranchise,scsellingregion
Integration.attributes.SKUSeasonSecondaryKeys=scspecialusage,sccreationtrack,scmatconstruction,sccolorwaylifecycle,scdistchannel,scdevelopmentype
Integration.attributes.seasonSecondaryKeys=seasonType,year
Integration.attributes.allowedSourcingStatus=development,confirmed,dropped
Integration.attributes.allowedLifeCycle=scsampleready,scbuyready
Integration.attributes.seasonsAllowed=scFallWinter,scSpringSummer
Integration.attributes.costSheetMileStones=scCrone,scPostcrone,scCrtwo,scPostcrtwo,scFinal
Integration.attributes.soureSeasonSecondaryKeys=scSourcingStatus
Integration.attributes.soureSecondaryKeys=scRegion
Integration.attributes.sourceSeasonStatus=scYes,scNo
#Integration.attributes.costSheetSecondaryKeys=scIncoterms,scIncotermlocation
com.lcs.wc.product.LCSSKUSeasonLink.ColorwayLifecycle.Status=scPLMPolorwayStatus
##HIT 294 Fix
Integration.attributes.skuSeason.sortingMultiListKeys=scdistchannel
## Integration End

##START : Product and Colorway Attribute Status Keys
com.lcs.wc.product.LCSSKUSeasonLink.ColorwayLifecycle.Status=sccolorwaylifecycle
com.lcs.wc.product.LCSProduct.ProductLifecycle.Status=scproductlifecycle
com.lcs.wc.product.LCSSKUSeasonLink.ColorwayLifecycle.BUYREADY.Status=scbuyready
com.lcs.wc.product.LCSSKUSeasonLink.ColorwayLifecycle.SAMPLEREADY.Status=scsampleready
com.lcs.wc.product.LCSSKUSeasonLink.ColorwayLifecycle.DROPPED.Status=scdropped
com.lcs.wc.product.LCSSKUSeasonLink.ColorwayLifecycle.PLANNED.Status=scPlanned
com.lcs.wc.product.LCSSKUSeasonLink.ColorwayLifecycle.RELEASED.Status=screleased
com.lcs.wc.product.LCSProduct.FlexType.Reebok=Apparel\\Reebok
com.lcs.wc.product.LCSProduct.FlexType.Footwear=Footwear\\Reebok
com.lcs.wc.color.LCSColor.FlexType.Colorway.Colors=Colorway Colors\\Reebok
com.lcs.wc.genrericMessage=Locked attributes cannot be updated.
com.lcs.wc.product.LCSSKUSeasonLink.genrericMessage=Locked attributes cannot be updated.
com.lcs.wc.product.ColorwaySeason.GenericErrorMessage=Colorway Lifecycle status cannot be changed to previous status.
com.lcs.wc.product.ColorwaySeason.ApprovalAtt.GenericErrorMessage=Approval or Sign-off attributes are mandatory,status cannot be changed to Buy Ready.
com.lcs.wc.product.LCSSKUSeasonLink.SentToS4.Keys.Yes=scYes
com.lcs.wc.product.LCSSKUSeasonLink.SentToS4.Keys.No=scNo
com.lcs.wc.product.LCSSKU.ObjectRef.color=color
com.lcs.wc.product.LCSSKU.COlorway.Name=skuName

com.lcs.wc.client.adminGroups.name=RBK_OPERATIONS,ADMINISTRATORS,LUCKY_SPARC_OPERATIONS

#Locked Attribute Keys 
com.lcs.wc.product.LCSSKU.LockedAttribute.Released.Status.Keys=color
com.lcs.wc.product.LCSSKU.LockedAttribute.SampleReady.Status.Keys=color
com.lcs.wc.product.LCSSKU.LockedAttribute.BuyReady.Status.Keys=color
com.lcs.wc.product.LCSProduct.LockedAttribute.Planned.Status.Keys=scBrand,scGender,scAge
com.lcs.wc.product.LCSProduct.LockedAttribute.Released.Status.Keys=scBrand,scGender,scAge,scSizeRange
com.lcs.wc.product.LCSProduct.LockedAttribute.BuyReady.Status.Keys=scBrand,scGender,scAge,scProductDescriptionShort,scSizeRange,scProductDescription
#Changes part of OCT 2024 Build and it will get populated throught sparc.xconf -- START
com.lcs.wc.product.LCSProductSeasonLink.LockedAttribute.SampleReady.Status.Keys=scDivision,scProductGroup,scsportcategory,sccorpmarketingline,scProductType
com.lcs.wc.product.LCSProductSeasonLink.LockedAttribute.BuyReady.Status.Keys=scDivision,scProductGroup,scsportcategory,sccorpmarketingline,scProductType
#Changes part of OCT 2024 Build and it will get populated throught sparc.xconf -- END
com.lcs.wc.color.LCSColor.LockedAttribute.Released.Status.Keys=scProductDescriptionShort,scColorDescription
com.lcs.wc.color.LCSColor.LockedAttribute.SampleReady.Status.Keys=scProductDescriptionShort,scColorDescription
com.lcs.wc.color.LCSColor.LockedAttribute.BuyReady.Status.Keys=scProductDescriptionShort,scColorDescription
com.sparc.jsp.product.disableSignOff.Attribute=sctestsignoff,scdevsignoff,sccustomssignoff


##END : Locked Attribute Status Keys

##Integration Atrrbutes 

com.lcs.wc.source.CostSheet.IntegrationAttributesKeys.INTEGRATION.ATT.KEYS=scIncoterms,scVendorCost,scMarketingroyalty,scUnitsOtherCosts,scTotalVendorCost,scIncotermlocation
com.lcs.wc.source.SourcingConfig.IntegrationAttributesKeys.INTEGRATION.ATT.KEYS=scFGFactory
com.lcs.wc.source.SourceToSeasonLink.IntegrationAttributesKeys.INTEGRATION.ATT.KEYS=scSourcingStatus,scprodleadtime

com.lcs.wc.product.LCSSKUSeasonLink.SentToS4.Flag=scSentToS4
com.lcs.wc.product.CostSheet.CostSentToS4.Flag=sccostcheetsenttos4
com.lcs.wc.source.SourcingConfig.SourcingSentToS4.Flag=scsourcingconfigsent
com.lcs.wc.product.LCSProduct.IntegrationAttributesKeys.APPAREL.REEBOK.INTEGRATION.ATT.KEYS=scPLMProductNo,scBrand,scGender,scProductDescriptionShort,scProductDescription,scworkingnumber,scbrandassetpartner,scfitsilhoette,scbenefits,sctechnology,scfeatures,scSizeRange
com.lcs.wc.product.LCSProduct.IntegrationAttributesKeys.FOOTWEAR.REEBOK.INTEGRATION.ATT.KEYS=scPLMProductNo,scBrand,scGender,scProductDescriptionShort,scProductDescription,scOutsole,sclining,scinlaysole,scupper,scoutsoledescription,scproductwidth,scfitsilhoette,scbrandassetpartner,scbenefits,sctechnology,scfeatures,scSizeRange
com.lcs.wc.product.LCSSKU.IntegrationAttributesKeys.INTEGRATION.ATT.KEYS=scColorwayNo,sclicensed,sclegacyarticle,scNRFcolorgroup,scNRFcolorcode
com.lcs.wc.product.LCSSKUSeasonLink.IntegrationAttributesKeys.INTEGRATION.ATT.KEYS=scspecialusage,sccreationtrack,scTargetRetail,scInitialEstimatedUnits,sccolorwaylifecycle,scmatconstruction,scRetailintrodate,scRetailexitdate,scdistchannel,scdevelopmentype
##com.lcs.wc.product.LCSProductSeasonLink.IntegrationAttributesKeys.INTEGRATION.ATT.KEYS=scDivision,scProductGroup,scProductType,scsportcategory,sccorpmarketingline,sccatmarketingline,scsalesline,sctechnologyconcept,scsustainabilityethics,scsellingregion,scFranchise,scprodmanager,scdistchannel,scRetailexitdate,scRetailintrodate,scTargetRetail,scdevelopmentype

com.lcs.wc.color.LCSPaletteLogic.addMaterialOrColorFromParentPalette.mode=2

com.lcs.wc.measurements.useIncrementalGrading=true

##Fit Information Changes

##Property entry to enable Quoted Measurment Column
jsp.testing.displayQuotedValues=true

##Property entry to enable Delta values Column
jsp.testing.displayDeltaValues=true

##Property entry to enable Comments column
jsp.testing.displayLineItemComments=true

 

#####Display Color options for fit samples#############
jsp.testing.FitApproval.ColorCriteria=true
com.lcs.wc.sample.LCSSample.includeColorway=true

##Property to default yes for the Include all Active cost sheet
jsp.sourcing.costing.default=active

FlexPLM.system.allowedFileTypesForUIDataLoaders=txt,csv,xls,xlsx,zip
FlexPLM.system.allowedFileTypesForContentFileUpload=stl,pdf,jpg,mp4,ai,,dxf,doc,xls,mpeg,wmv,avi,tiff,gif,docx,ppt,pptx,txt,xlsx,csv,json,zip

## Property entry for arranging the attributes of Vendor on Sourcing Config page
com.lcs.wc.vendor.attributes=scPLMVendorSupplierNo,scPLMVendorSupplierStatus,scReebokStatus,scLuckyStatus,scAeroStatus,scNauticaStatus,scvendorlegacycode,scbrandcomments,scManagingoffice,scSAPVendorNo,scSAPVendorName,scFullCircleVendorNoLucky,scSAPVendorNameLucky,scSCMNumberF21,scvendorlegacycodeAero,scManagingOfficeAero,scvendorlegacycodeNautica,scGlobalOrganicTextileStandardsGOTS,scRecycledClaimStandardRCS,scProductType,scManufacturingCapabilities,scAuthorizedforColorTesting,scColorTestingExpiration,scAuthorizedforMaterialTesting,scMaterialTestingExpiration,scVendorGroup1,scCommentsLucky,scManagingOfficeLucky
com.lcs.wc.vendor.flextype=Vendor (Supplier)\\Vendor



##Tech Pack Share File integration
com.sparc.wc.specification.pdfExportQueueName=SPARCShareFileQueue
com.sparc.wc.product.SPARCExternalPartnerTechPackGenPlugin.BrandKey=scBrand
com.sparc.wc.product.SPARCExternalPartnerTechPackGenPlugin.divisionKey=scProductDivision
com.sparc.wc.product.SPARCExternalPartnerTechPackGenPlugin.ExternalPartenersKey=scPartner
com.sparc.wc.product.SPARCExternalPartnerTechPackGenPlugin.SpecStatusKey=scSpecStatus
com.sparc.wc.product.SPARCExternalPartnerTechPackGenPlugin.SpecStatusVal=final
com.sparc.wc.product.SPARCExternalPartnerTechPackGenPlugin.lastSentKey=scTechPackLastSent
com.sparc.wc.product.SPARCExternalPartnerTechPackGenPlugin.resendTPKey=scResendTechPack
com.lcs.wc.product.SPARCPDFMultiSpecGenerator.includeOnTPKey=scIncludeinTechPack
com.sparc.wc.businessObject.SPARCTechPackShareUtil.externalPArtnerType=Business Object\\scShareFile
com.sparc.wc.businessObject.SPARCTechPackShareUtil.pathKey=scShareFilePath
com.sparc.wc.season.SPARCTechPackShareUtil.devSeason=seasonType
com.sparc.wc.season.SPARCTechPackShareUtil.devYear=year
com.sparc.wc.season.SPARCTechPackShareUtil.divisionKey=scProductDiv
com.sparc.wc.product.SPARCExternalPartnerTechPackGenPlugin.apiCallString=Upload File to ShareFile
com.sparc.wc.product.SPARCExternalPartnerTechPackGenPlugin.PLMProductNumKey=scPLMProductNo
com.sparc.wc.foundation.LCSLogEntry.shareFileIntegrationLogEntry.flexTypePath=Log Entry\\scShareFileIntegrationLogEntry
com.sparc.wc.foundation.LCSLogEntry.shareFileIntegrationLogEntry.apiCallType=scAPICallType
com.sparc.wc.foundation.LCSLogEntry.shareFileIntegrationLogEntry.request=scRequest
com.sparc.wc.foundation.LCSLogEntry.shareFileIntegrationLogEntry.response=scResponse
com.sparc.wc.foundation.LCSLogEntry.shareFileIntegrationLogEntry.requestTime=scRequestTime
com.sparc.wc.foundation.LCSLogEntry.shareFileIntegrationLogEntry.responseTime=scResponseTime
com.sparc.wc.foundation.LCSLogEntry.shareFileIntegrationLogEntry.status=scStatus
com.sparc.wc.foundation.LCSLogEntry.shareFileIntegrationLogEntry.plmProductNo=scPLMProductNo
com.sparc.wc.foundation.LCSLogEntry.shareFileIntegrationLogEntry.season=scSeason
com.sparc.wc.foundation.LCSLogEntry.shareFileIntegrationLogEntry.specification=scSpecification
com.sparc.wc.foundation.LCSLogEntry.shareFileIntegrationLogEntry.partner=scPartner

#### Increase of Sample COnsole Query Limit ###
com.lcs.wc.sample.query.SampleConsoleQuery.queryLimit=10000











#-*- XCONF CONTENT START -*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-
#
#     ****    DO NOT MODIFY THE CONTENTS OF THIS FILE DIRECTLY!    ****
#     ****            SEE COMMENT AT TOP FOR DETAILS               ****
#
com.lcs.wc.product.LCSProduct.LockedAttribute.SampleReady.Status.Keys=scBrand,scGender,scAge,scProductDescriptionShort,scSizeRange,scProductDescription
com.lcs.wc.product.LCSProductSeasonLink.IntegrationAttributesKeys.INTEGRATION.ATT.KEYS=scDivision,scProductGroup,scProductType,scsportcategory,sccorpmarketingline,sccatmarketingline,scsalesline,sctechnologyconcept,scsustainabilityethics,scsellingregion,scFranchise,scprodmanager,scdistchannel,scRetailexitdate,scRetailintrodate,scTargetRetail,scdevelopmentype
#Changes part of OCT 2024 Build and it will get populated throught sparc.xconf -- START
com.lcs.wc.product.LCSProductSeasonLink.LockedAttribute.Released.StatusKeys=scDivision,scProductGroup,scsportcategory,sccorpmarketingline,scProductType
#Changes part of OCT 2024 Build and it will get populated throught sparc.xconf -- END
#
#     ****    DO NOT MODIFY THE CONTENTS OF THIS FILE DIRECTLY!    ****
#     ****            SEE COMMENT AT TOP FOR DETAILS               ****
#
#-*- XCONF CONTENT END -!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-!-*-
