HEADER=com.lcs.wc.product.PDFProductSpecificationHeader
HEADER1=com.sparc.wc.product.SPARCPDFProductSpecificationHeader1
HEADER2=com.sparc.wc.product.SPARCPDFProductSpecificationHeader2
HEADER3=com.sparc.wc.product.SPARCPDFProductSpecificationHeader3
Header Page=com.sparc.wc.product.SPARCPDFProductSpecificationProductThumbnail
Colorways=com.sparc.wc.product.SPARCPDFProductSpecificationColorways
#HEADER3=com.sparc.wc.product.PDFProductSpecificationHeaderM
#HEADER4=com.sparc.wc.product.PDFProductSpecificationHeaderM

##INSERT CUSTOM HEADERS HERE - START - HARSHAD
#MeasurementsHeader=com.lcs.wc.product.PDFProductSpecificationHeaderM
#MeasurementsHeader=com.lcs.wc.product.PDFProductSpecificationHeader
##INSERT CUSTOM HEADERS HERE - END
Images Page=com.lcs.wc.product.PDFImagePagesCollection2
Construction=com.lcs.wc.product.PDFProductSpecificationConstruction2|orientation=LANDSCAPE
BOM=com.sparc.wc.product.SPARCPDFProductSpecificationBOM2|orientation=LANDSCAPE
Measurements=com.lcs.wc.product.PDFProductSpecificationMeasurements2|orientation=LANDSCAPE
#Sample=com.sparc.wc.product.SPARCPDFProductSpecificationSample2|orientation=LANDSCAPE

CHANGE_TRACKING=com.lcs.wc.product.ChangeTrackingPDFGenerator
CADDOC_VARIATIONS=com.lcs.wc.epmstruct.PDFCadDocVariationsGenerator
SPEC_PART_REPORT=com.lcs.wc.partstruct.PDFPartVariationsGenerator
##BOMHeader=com.lcs.wc.flexbom.gen.BOMAttributesPDFContent
##BOMFooter=com.lcs.wc.flexbom.gen.BOMAttributesPDFContent
#MeasurementsHeader=com.lcs.wc.measurements.gen.MeasAttributesPDFContent
#MeasurementsFooter=com.lcs.wc.measurements.gen.MeasAttributesPDFContent
#ConstructionHeader=com.lcs.wc.construction.gen.ConstructionAttributesPDFContent
#ConstructionFooter=com.lcs.wc.construction.gen.ConstructionAttributesPDFContent
#SpecCadDocVariationHeader=
#SpecCadDocVariationFooter=
#SpecPartVariationHeader=
#SpecPartVariationFooter=
