sampleRequestComments=com.sparc.wc.sample.gen.SPARCSampleDetailsPDFContent
sampleFitPhotoCorrectionsImagePage=com.sparc.wc.sample.gen.SPARCSampleFitPhotoCorrectionsPDFContent
sampleRequestFitDetails=com.sparc.wc.sample.gen.SPARCSampleRequestFitDetailsPDFContent
#fitInformation=com.sparc.wc.sample.gen.SPARCFitInformationPDFContent
#sampleImagePages=com.sparc.wc.sample.gen.SPARCSampleImagesPDFContent