#HEADER=com.lcs.wc.product.PDFProductSpecificationHeader
#Cover Page=com.lcs.wc.product.PDFImagePagesCollection|pageType=coverpage
#Detail Sketch=com.lcs.wc.product.PDFImagePagesCollection|pageType=detailSketch
#Front Sketch=com.lcs.wc.product.PDFImagePagesCollection|pageType=frontSketch
#Construction Image Page=com.lcs.wc.product.PDFImagePagesCollection|pageType=construction
Construction=com.lcs.wc.product.PDFProductSpecificationConstruction
#Measurements Image Page=com.lcs.wc.product.PDFImagePagesCollection|pageType=measurements

#Pattern Corrections Image Page=com.lcs.wc.product.PDFImagePagesCollection|pageType=patternCorrections





Cover Page=com.lcs.wc.product.PDFImagePagesCollection|pageType=coverpage
#Detail Sketch=com.lcs.wc.product.PDFImagePagesCollection|pageType=detailSketch
Front Sketch=com.lcs.wc.product.PDFImagePagesCollection|pageType=frontSketch
#Construction Image Page=com.lcs.wc.product.PDFImagePagesCollection|pageType=construction

#Measurements Image Page=com.lcs.wc.product.PDFImagePagesCollection|pageType=measurements

#Pattern Corrections Image Page=com.lcs.wc.product.PDFImagePagesCollection|pageType=patternCorrections

Artwork=com.lcs.wc.product.PDFImagePagesCollection|pageType=artwork
Back Sketch=com.lcs.wc.product.PDFImagePagesCollection|pageType=backsketch
Colorway Image=com.lcs.wc.product.PDFImagePagesCollection|pageType=colorwayimage
Construction Detail=com.lcs.wc.product.PDFImagePagesCollection|pageType=constructiondetail
Croquis Sketch=com.lcs.wc.product.PDFImagePagesCollection|pageType=croquissketch
Quick Spec=com.lcs.wc.product.PDFImagePagesCollection|pageType=quickSpec
Fit Photo / Corrections=com.lcs.wc.product.PDFImagePagesCollection|pageType=fitphotocorrections
Folding / Packing / Shipping=com.lcs.wc.product.PDFImagePagesCollection|pageType=foldingpackingshipping
Inspiration / Reference Photo=com.lcs.wc.product.PDFImagePagesCollection|pageType=inspirationreferencephoto
Measurement Detail=com.lcs.wc.product.PDFImagePagesCollection|pageType=measurementdetail
Trim / Label Placement=com.lcs.wc.product.PDFImagePagesCollection|pageType=trimlabelplacement
Wash Image=com.lcs.wc.product.PDFImagePagesCollection|pageType=washimage
Design Detail=com.lcs.wc.product.PDFImagePagesCollection|pageType=designdetail
Design Pack=com.lcs.wc.product.PDFImagePagesCollection|pageType=scdesignpack


BOM=com.lcs.wc.product.PDFProductSpecificationBOM
Measurements=com.lcs.wc.product.PDFProductSpecificationMeasurements