##colorwayReport=com.lcs.wc.flexbom.gen.MatColorPDFContent
#sizingReport=com.lcs.wc.flexbom.gen.SizePDFContent
#singleBOM=com.lcs.wc.flexbom.gen.SingleBOMPDFContent

colorwayReport=com.sparc.wc.flexbom.gen.SPARCMatColorPDFContent
#sizingReport=com.sparc.wc.flexbom.gen.SPARCSizePDFContent
singleBOM=com.sparc.wc.flexbom.gen.SPARCSingleBOMPDFContent