##Product attributes
##Product^placeholderStatus:true|ALL

##Product^placeholderName:true|ALL
##Product^productName:true|ALL
##Product^scPLMProductNo:true|ALL


Product^scSizeRange:true|ALL
Product^scProductDescriptionShort:true|ALL 
Product^scProductDescription:true|ALL



##Product Season attributes

Product^scproductlifecycle:true|ALL
Product^sccatmarketingline:true|ALL
Product^scsalesline:true|ALL
Product^scdevelopmentype:true|ALL
	


## Colorway Level attributes
Product^scNRFcolorcode:true|ALL



##Colorway Season attributes

Product^sccustomssignoff:true|ALL
Product^scBuyReadyDate:true|ALL
Product^scearlybuyready:true|ALL
Product^sccolorwaylifecycle:true|ALL
Product^scRetailintrodate:true|ALL
Product^sccreationtrack:true|ALL
Product^scspecialusage:true|ALL
Product^scdevelopmentype:true|ALL

	



















