com.sparc.wc.product.SPARCTechPackShare.username=
com.sparc.wc.product.SPARCTechPackShare.password=
com.sparc.wc.product.SPARCTechPackShare.hostname=
com.sparc.wc.product.SPARCTechPackShare.clientId=
com.sparc.wc.product.SPARCTechPackShare.clientSecret=