## Costing uploader and dowloader

com.sparc.wc.costsheet.uploaderQueueName=CostUploaderProcessingQueue

com.sparc.wc.costsheet.detailedtemplateMappings.FOOTWEAR=template-detailed-footwear.xlsx
com.sparc.wc.costsheet.detailedtemplateMappings.APPAREL=template-detailed-apparel.xlsx


com.sparc.wc.bomlink.section.scFwUpper=scAdditionalUpper
com.sparc.wc.bomlink.section.scSockliner=scAdditionalSockliner
com.sparc.wc.bomlink.section.scInsole=scAdditionalInsole
com.sparc.wc.bomlink.section.scsundries=scAdditionalSundries
com.sparc.wc.bomlink.section.scPackaging=scAdditionalPackaging
com.sparc.wc.bomlink.section.scBottom=scAdditionalBottom

com.sparc.wc.bomlink.section.mainmaterials=scAdditionalMainMaterials
com.sparc.wc.bomlink.section.sctrims=scAdditionalTrims
com.sparc.wc.bomlink.section.sclining=scAdditionalLining
com.sparc.wc.bomlink.section.scartwork=scAdditionalArtwork
com.sparc.wc.bomlink.section.scprocess=scAdditionalProcess
com.sparc.wc.bomlink.section.labels=scAdditionalLabels
com.sparc.wc.bomlink.section.packaging=scAdditionalPackaging

com.sparc.wc.bo.flextype.FOOTWEAR=Business Object\\scFootWearBreakDownBO
com.sparc.wc.bo.flextype.APPAREL=Business Object\\scApparelBreakDownBO

com.sparc.wc.document.flextype.FOOTWEAR=Document\\scFootWearBreakDown
com.sparc.wc.document.flextype.APPAREL=Document\\scApparelBreakDown


com.sparc.wc.upload.costsheet.attributes=scMilestoneStatus,scIncoterms,scFirstSaleMarkup,scVendorCostComments
com.sparc.wc.upload.bomlink.attributes=priceOverride,scCIF,quantity,lossAdjustment,scCalculationSizePercent

# costing uploader changes - start
jsp.sparc.sourcing.SPARCDownloadCostSheetData.highLevelCSDownloadZipFileName=CostSheet_HighLevelDownload
jsp.sparc.sourcing.SPARCDownloadCostSheetData.detailedCSDownloadZipFileName=CostSheet_DetailedDownload
jsp.sparc.season.SPARCLinePlanHeader.breakdownDownloadAction=Costing - Detailed Breakdown Download
jsp.sparc.season.SPARCLinePlanHeader.highLevelDownloadAction=Costing – High Level Download
jsp.sparc.season.SPARCLinePlanHeader.productDivisionKey=scProductDiv
jsp.sparc.season.SPARCLinePlanHeader.breakdownUploadAction=Costing - Detailed Breakdown Upload
jsp.sparc.season.SPARCLinePlanHeader.highLevelUploadAction=Costing – High Level Upload
jsp.sparc.season.SPARCLinePlanHeader.applicableViews=Costing - Upload/Download View
jsp.sparc.season.SPARCLinePlanHeader.maxSelectionLimit=500
jsp.sparc.season.SPARCLinePlanHeader.ProductToCostsheetTypeMapping=Product\\scApparel\\scAeropostale~Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelAeropostale:Cost Sheet\\scSparc\\scApparelBreakdown\\scApparelBreakdownAeropostale,Product\\scApparel\\scForever21~Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelForever21:Cost Sheet\\scSparc\\scApparelBreakdown\\scApparelBreakdownForever21,Product\\scApparel\\scLucky~Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelLucky:Cost Sheet\\scSparc\\scApparelBreakdown\\scApparelBreakdownLucky,Product\\scApparel\\scReebok~Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelReebok:Cost Sheet\\scSparc\\scApparelBreakdown\\scApparelBreakdownReebok,Product\\scFootwear\\scFootwearReebok~Cost Sheet\\scSparc\\scFootwearBreakdown\\scFootwearBreakdownReebok:Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelReebok,Product\\scApparel\\scNautica~Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelNautica:Cost Sheet\\scSparc\\scApparelBreakdown\\scApparelBreakdownNautica
jsp.sparc.season.SPARCLinePlanHeader.DivisionMapping=scNonApparel~NONAPPAREL,sclicensed~LICENSEDAPP,sclicensedftw~LICENSEDFTW,schardware~HARDWARE,apparel~APPAREL,footwear~FOOTWEAR
jsp.sparc.sourcing.highLevelCSTemplate.allowedFileTypes=zip,xlsx
jsp.sparc.sourcing.highLevelCSTemplate.costSheetHighLevelUploadHeading=CostSheet High Level Upload
jsp.sparc.sourcing.highLevelCSTemplate.uploadFileLabel=Upload File
jsp.sparc.sourcing.highLevelCSTemplate.noFileSelectedMessage=No file selected for upload
jsp.sparc.sourcing.highLevelCSTemplate.invalidFieFormatMessage=File selected with invalid format, Allowed formats are zip or xlsx
jsp.sparc.sourcing.highLevelCSTemplate.highLevelUploadStatusMessage=The file upload has been started in the background. Please check the Business Object Apparel High Level after sometime
com.sparc.wc.costsheet.uploader.SPARCHighLevelCostSheetUploader.Template=HIGHLEVEL_APPAREL_template.xlsx
com.sparc.wc.costsheet.uploader.SPARCHighLevelCostSheetUploadHelper.docType.APPAREL=Document\\scApparelHighLevel
jsp.sparc.sourcing.UploadDetailCSFWTemplate.detailUploadStatusMessage=The file upload has been started in the background. Please check the Business Object Footwear Detailed Breakdown Upload Status after sometime
jsp.sparc.sourcing.UploadDetailCSAPPTemplate.detailUploadStatusMessage=The file upload has been started in the background. Please check the Business Object Apparel Detailed Breakdown Upload Status after sometime


com.sparc.wc.costsheet.uploader.SPARCHighLevelCostSheetUploadHelper.csHighLevelEditableAttributes=name,scMilestoneStatus,scVendorCostSheetStatus,scIncoterms,scIncotermlocation,scDestination,scAdditionalBuy,scQuoteGoodUntil,scQuoteUnits,scMainMaterialUnitPrice,scMainMaterialYield,scVendorCost,scMarketingroyalty,scUnitsOtherCosts,scHangerCost,scFirstSaleMarkup,scStyleMOQ,scColorMOQ,scMOQComments,scLeadTimePOtoShip,scVendorCostComments,scCostSheetStatus
com.sparc.wc.costsheet.uploader.SPARCHighLevelCostSheetUploadHelper.csHighLevelCreateableAttributes=name,scMilestoneStatus,scVendorCostSheetStatus,scIncoterms,scIncotermlocation,scDestination,scAdditionalBuy,scQuoteGoodUntil,scQuoteUnits,scMainMaterialUnitPrice,scMainMaterialYield,scVendorCost,scMarketingroyalty,scUnitsOtherCosts,scHangerCost,scFirstSaleMarkup,scStyleMOQ,scColorMOQ,scMOQComments,scLeadTimePOtoShip,scVendorCostComments,scCostSheetStatus
com.sparc.wc.costsheet.uploader.SPARCHighLevelCostSheetUploadHelper.csHighLevelAttrKeyValuePair=name~Cost Sheet Name,scMilestoneStatus~Cost Sheet Milestone,scVendorCostSheetStatus~Vendor Cost Sheet Status,scIncoterms~Incoterms,scIncotermlocation~Incoterms Location,scDestination~Destination,scAdditionalBuy~Additional Buy,scQuoteGoodUntil~Quote Good Until,scQuoteUnits~Quote Units,scMainMaterialUnitPrice~Main Material Unit Price,scMainMaterialYield~Main Material Yield,scVendorCost~Vendor Product Cost Override,scMarketingroyalty~Marketing Royalty $ - US,scUnitsOtherCosts~Other Vendor Costs,scHangerCost~Hanger Cost,scFirstSaleMarkup~First Sale Markup,scStyleMOQ~Style MOQ,scColorMOQ~Color MOQ,scMOQComments~MOQ Comments,scLeadTimePOtoShip~Lead Time (PO to Ship),scVendorCostComments~Vendor Cost Comments,scCostSheetStatus~Internal Cost Sheet Status
com.sparc.wc.costsheet.uploader.SPARCHighLevelCostSheetUploadHelper.csHighLevelRequiredAttributes=Incoterms~scIncoterms,
com.sparc.wc.costsheet.uploader.SPARCHighLevelCostSheetUploadHelper.csHighLevelObjectRefAttributes=scIncotermlocation,
com.sparc.wc.costsheet.uploader.SPARCHighLevelCostSheetUploadHelper.csHighLevelMandatortAttsforCreate=productName,costSheetType,seasonName,plmSourceName,specName,costSheetSelectedColorwayNames,representativeColorwayName,scIncoterms
com.sparc.wc.costsheet.uploader.SPARCHighLevelCostSheetUploadHelper.costSheetTypeInternalDisplayNameMapping=Cost Sheet Product\\Sparc\\High Level\\Aeropostale~Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelAeropostale,Cost Sheet Product\\Sparc\\High Level\\Forever 21~Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelForever21,Cost Sheet Product\\Sparc\\High Level\\Lucky~Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelLucky,Cost Sheet Product\\Sparc\\High Level\\Reebok~Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelReebok
com.sparc.wc.costsheet.uploader.SPARCHighLevelCostSheetUploadHelper.costSheetTypeDisplayNames=Cost Sheet Product\\Sparc\\High Level\\Aeropostale,Cost Sheet Product\\Sparc\\High Level\\Forever 21,Cost Sheet Product\\Sparc\\High Level\\Lucky,Cost Sheet Product\\Sparc\\High Level\\Reebok
com.sparc.wc.costsheet.uploader.SPARCHighLevelCostSheetUploader.Template=HIGHLEVEL_APPAREL_template.xlsx
# costing uploader changes - end


##Start of Additional and Override attributes
com.sparc.wc.ftw.costsheet.overrideattributes=scUpperOverride,scSocklinerOverride,scInsoleOverride,scBottomOverride,scSundriesOverride,scPackagingOverride
com.sparc.wc.ftw.costsheet.additionalattributes=scAdditionalUpper,scAdditionalSockliner,scAdditionalInsole,scAdditionalBottom,scAdditionalSundries,scAdditionalPackaging


com.sparc.wc.app.costsheet.overrideattributes=scMainMaterialsOverride,scTrimsOverride,scLiningOverride,scArtworkOverride,scProcessOverride,scLabelsOverride,scPackagingOverride
com.sparc.wc.app.costsheet.additionalattributes=scAdditionalMainMaterials,scAdditionalTrims,scAdditionalLining,scAdditionalArtwork,scAdditionalProcess,scAdditionalLabels,scAdditionalPackaging
##End of Override attributes
	