com.sparc.wc.costing.HTSCodes=scHTSCode1~scHTSCode1WeightPercent,scHTSCode2~scHTSCode2WeightPercent,scHTSCode3~scHTSCode3WeightPercent,scHTSCode4~scHTSCode4WeightPercent

##scHTSCode4~scHTSCode4WeightPercent

com.sparc.wc.costing.hts.scHTSCode1=scDutyPercent1US~scTariffPercent1US~scFlatDutyDollars1US~scHTSCode1WeightPercent
com.sparc.wc.costing.hts.scHTSCode2=scDutyPercent2US~scTariffPercent2US~scFlatDutyDollars2US~scHTSCode2WeightPercent
com.sparc.wc.costing.hts.scHTSCode3=scDutyPercent3US~scTariffPercent3US~scFlatDutyDollars3US~scHTSCode3WeightPercent
com.sparc.wc.costing.hts.scHTSCode4=scDutyPercent4US~scTariffPercent4US~scFlatDutyDollars4US~scHTSCode4WeightPercent

##com.sparc.wc.costing.tariff.scHTSCode1=scTariffPercent1US
##com.sparc.wc.costing.tariff.scHTSCode2=scTariffPercent2US
##com.sparc.wc.costing.tariff.scHTSCode3=scTariffPercent3US
##com.sparc.wc.costing.tariff.scHTSCode4=scTariffPercent4US

com.sparc.wc.costing.region=USA
com.sparc.wc.costing.HTSBOFlexType=Business Object\\scHTSLookUpTable

com.sparc.wc.costing.FreightBOFlexType=Business Object\\scFrieghtLookUpTable

com.sparc.wc.costing.InternalLoadFlexType=Business Object\\scInteralLoadLookupTable

com.sparc.wc.costing.TariffByCountry=Business Object\\scTariffByCountry

com.sparc.wc.costing.OtherBOFlexType=Business Object\\scOtherLookupTable

com.sparc.wc.costing.FreightAttributes=scBrand~scBrand~text~nonBlank,scShipMode~scShipMode~text~nonBlank,scDestination~scDestination~text~blank,scCountryofOrigin~scCountryOfOrigin~objectref~blank,scDestinationCountryUSA~scDestinationCountry~objectref~nonBlank,scCategory1~scCategory1~text~nonBlank,scCategory2~scCategory2~text~blank

com.sparc.wc.costing.InternalLoadAttributes=scBrand~scBrand~text~nonBlank,

com.sparc.wc.costing.OtherLoadAttributes=scBrand~scBrand~text~nonBlank,

com.sparc.wc.costing.attributes=scDutyPercent1US,scDutyPercent2US,scDutyPercent3US,scDutyPercent4US,scFlatDutyDollars1US,scFlatDutyDollars2US,scFlatDutyDollars3US,scFlatDutyDollars4US,scTariffPercent1US,scTariffPercent2US,scTariffPercent3US,scTariffPercent4US,scFreight1DollarsUS,scInternalLoad1Percent,scOtherPercentUS,scHTSCode1WeightPercent,scHTSCode2WeightPercent,scHTSCode3WeightPercent,scHTSCode4WeightPercent,scHTSMatchingRow,scFreightMatchingRow,scInternalMatchingRow,scOtherMatchingRow

###Properties to populate non-calculated attributes onto the Costsheet from Other sources - start###
com.lcs.wc.product.CostSheet.productLevelAttributes=scBrand|~*~|scBrand
com.lcs.wc.product.CostSheet.productORColorwayLevelAttributes=scVendorTargetCost|~*~|scTargetVendorQuote,scTargetFOB|~*~|scTargetFOB,scTargetLandedCost|~*~|scTargetLandedCostDollarsUS,scTargetRetail|~*~|scTargetRetail,scTargetIMU|~*~|scTargetIMU
com.lcs.wc.product.CostSheet.sourcingLevelAttributes=
com.lcs.wc.product.CostSheet.sourcing2ndLevelAttributes=AgentOffice~scFGFactory~scCountry|~*~|scCountryofOrigin


##Changes done as part of Costing uploader as downloader requires highLevelCost to download - Start
Product.scApparel.scLucky=Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelLucky
##Product.scApparel.scReebok=Cost Sheet\\scSparc\\scApparelBreakdown\\scApparelBreakdownReebok
Product.scApparel.scReebok=Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelReebok
Product.scApparel.scForever21=Cost Sheet\\scSparc\\scApparelBreakdown\\scApparelBreakdownForever21
Product.scApparel.scAeropostale=Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelAeropostale
##Product.scFootwear.scFootwearReebok=Cost Sheet\\scSparc\\scFootwearBreakdown\\scFootwearBreakdownReebok
Product.scFootwear.scFootwearReebok=Cost Sheet\\scSparc\\scApparelHighLevel\\scApparelHighLevelReebok
Product.scApparel.scNautica=Cost Sheet\\scSparc\\scApparelBreakdown\\scApparelBreakdownNautica
##Changes done as part of Costing uploader as downloader requires highLevelCost to download - End



#Properies used in BOM Rollup Plugin - start
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.MaterialPriceKey=materialPrice
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.PriceOverrideKey=priceOverride
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.CIFKey=scCIF
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.GrossQuantityKey=scGrossQuantity
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.RetrievefromBOMKey=scRetrievefromBOM
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.BOMKey=scBOM
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.BOMIterationKey=scBOMIteration
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.BOMRetrieveKey=scBOMRetrieveDate
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.BOMSectionKey=section
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.SPARC_CUSTOMREP_COLORWAY_FOR_BOM_ROLLUP=SPARC_CUSTOMREP_COLORWAY_FOR_BOM_ROLLUP
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.SPARC_REFRESH_MULTI_COSTSHEET_FOR_BOM_ROLLUP=SPARC_REFRESH_MULTI_COSTSHEET_FOR_BOM_ROLLUP
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.sectionKeyToBOMAttrMapping=mainmaterials~scBOMMainMaterials,sctrims~scBOMTrims,scartwork~scBOMArtwork,scprocess~scBOMProcess,labels~scBOMLabels,packaging~scBOMPackaging,sclining~scBOMLining
com.sparc.wc.flexbom.SPARCBOMRollupPlugin.Footwear.sectionKeyToBOMAttrMapping=scFwUpper~scBOMUpper,scSockliner~scBOMSockliner,scInsole~scBOMInsole,scBottom~scBOMBottom,scsundries~scBOMSundries,scPackaging~scBOMPackaging
#Properies used in BOM Rollup Plugin - end
