##############################################################################
#
#  release.properties
#    Release Note for Simple Change Framework 
#
#               _.-._
#           _.-|_|_|_|-._
#       _.-|`-._ `-|_|_|_|-._
#   _.-|_|_|_|-'  _  `-|_|-' |-._
#  |_|_|_|-'  _.-' `-._      |-|_|             _
#  |_|-'   .-'         `-.   |-|_|         _.-'
#  |      |`-._       _.-'|  |-|_|        |_       _.-
#  |_.-|  |    `-._.-'    |  |-|_|      _   `-._.-'   _ 
#  |_|-|  |       |       |  |-|_|     | `-._     _.-' |
#  |_|-|  |       |       |  |-' |     |_    |   | 
#  |_|-|  |_      |      _|     _|       `-._    |_.-|
#  |_|-|    `-._  |  _.-'   _.-|_|     |_    |   |     .
#  |_|-|   ._   `-|-'   _.-|_|_|_|       `-._|   |
#    `-|   |_|-._     -|_|_|_|-'
#       `-.|_|_|_|-._  `_|-'
#            `-|_|_|_|-'
#                `-'
#
sic.version=v1.1.7
sic.version.hotfix=12
##############################################################################
#
# 1.1.7  Exporters, use tar with GNU (for long file) before converting to Zip
#	  Include xconf.r to support removing a property from an existing multi-valued property 
#	  Skip execution of SQL files already successfully imported
#	  Include dedicated AddColumns macrodef for FlexPLM 12.1 and more
#	  Manage definition exporter failure use case (if not file is generated, do not fail the deployment, log error and continue to next step)
#	  Skip MakeJar operation if Windchill release is greater than 12.x, can still be re-enforced using property force.makejar=true
#	  Add compilation option to use.runtime.classpath (defined in tools.xml) for compilation. 
#	  BAC updates, surround BAC loader with Loggers, add support for ConflictResolution and Mapping files
#	  Exporters, default to UTF-8 during Zip operation to support files with specific characters
#	  Include SchemaConfig.xml file support (Windchill version >= 12.0)
#	  Replace all nashorn dependencies with groovy
# 	  Include Exporters for Type, Enum, ABSR, AGVR and LCSFiles
#	  Include changes required after Nashorn library removal from Java 156.
#		Update Required starting with Windchill Panther.
#	  Include extra FlexPLM Macrodefs to disable and re-enable extra MethodServer and BackgroundMethodServer during installation
#	  Include parameter enforce=true on loadFromFile and loadFileSet macrodef: default="false"
#	  Update importBAC macrodef to support authentication via trustedAuth
#
# 1.1.6   Remove Log4J dependency from Custom Handler LoadDeleteAccessControlRules
#	  Replace "servlet/ProwtGW" by "servlet/WindchillGW/wt.httpgw.HTTPServer/ping" to verify that Method Server is Up and Running
#		Since Windchill Marlin, ProwtGW requires authentication which is not necessary at this time.
#	  Execute windchill Restart action from Windchill Home directory
#	  Remove all dependencies to xmlpath library - replaced by groovy
#	  Load Preferences, add default value to parameter level.
#	  Refactor install.xml, remove duplicated code and reorder install.tp specific installation types.
#	  Fix installation started with wrong user; was not failing when installation.type was already set.
#	  Archive and Remove Previous Logs during consecutive executions of same build.
#	  Fix LoadFiles generated by the SoftType Loader containing character $, Rename the file and replace $ per _ before executing the Load command.
#	  Add more Details while displaying the version.
#	  Include isgreaterthan macrodef to be able to compare 2 numbers.
#	  Add new property "auto.disable.prime.type.cache" to surround the Load File sequence. 
#	  Manage dedicated "buildhistory" folder as md5 database home
#		Can be configured changing property "builds.history.dir" in build.properties
#	  Include Validation Mode property test_mode=true can be used to activate this mode.
#		Using this mode, no changes will be applied on the Server, but most steps will be logged and tested
#			Compilation will happen, but no class nor jar will be modified on WT_HOME
#	  Update Compilation task to not fail the full package and log compilation status in the DeliveryNote (to supports upgrades with known sources)
#	  Include dedicated error.log file
#		Add error message dedicated to Load Missing Files
#		Add error message dedicated to Command Execution Exceptions
#		Add error message dedicated to Compilation Issues
#
# 1.1.5   Fix Log issue (after first Failure, other LoadFiles was listed as ERROR on the DN whatever their execution status)
#	  Fix md5 registration issue (all md5 files was registered on the same subfolder)
#	  Include loadCSVLoadFile macrodef (LoadFromFile with CSV files)
#	  Include LDAP Import "ldif.import"
#	  Include Add Columns TypeInfo Generator "add.columns"
#	  Include SQLCommandTool execution "execute.sql.command"
#	  Include new installation.type to build container image "44"
#	  Exclude wc3rdpartylibs.jar from compilation classpath
#	  Update checkAuth to skip control in case the server is down (while building the image)
#	  Include "updateEditDTDUtility"
#	  Include "backupExistingLWCTypeImpExpFiles" and "loadLWCTypeImpExpFiles"
#		Two properties added to build.properties lwctypeimpexp.autodeletetypes and lwctypeimpexp.autodeleteattributes defaulted to "false"	
#		These two functions are surrounding the load.files execution to remove the manual post step relative to Attribute or Type Deletion.	
#	  Include "disablePrimeTypeCache" and "enablePrimeTypeCache"
#	  Include "encryptAllPasswords" and "encryptValueOfProperty"
#
# 1.1.4   Fix Windows path issue appearing while registering checksum to identify already successfully loaded files
#	  Include ways to update Log4J property file "addToPropertyFile"
#	  Include Log4J addition tool "appendToLog4JMethodServerPropertyFile"
#	  Include Generic Merge Property files tool "mergePropertyFiles"
#
# 1.1.3   Include Incremental Load feature; do not reload a file already loaded on a previous attempt or even a previous build.
#		Option can be activated via property  skip.already.loaded.files=true  added to build.properties
#	  Add AddToProperty xconf.a macrodef
#	  Remove dependancy to the Ant-Class Loader (incompatible with Windchill 12/Java 11)
#	  Replace the default user "Administrator" by "wcadmin" (there's no alternate name for wcadmin user in Windchill 12)
#
# 1.1.2   Bug Fix of deleteFile macrodef
#	  Addition of deleteFolder macrodef
#
# 1.1.1   First Release supported by Automated Deployment process
#
# 1.0.7   Last Stable Release of Simple Change 1.0
#
############
