##########################################################################
#
# File: clientSidePluginManagerMappings.properties
#
# This file is used to map specific specific Client Side Plugin JSPs    
# to the generation of specific Flextype pages. 
# No user customizations should be made to this file. If a user, Administrator, 
#  Developer etc. needs to create settings to apply to their local environment, 
# then copy this file and renamed it to custom.clientSidePluginManagerMappings.properties
# and it should be in your /codebase/com/lcs/wc/client/web directory.
# 
# The format is <FlextypePath>.<activity>.<action>.<clientSidePluginType>=<file Path>
# <FlextypePath> = RootType.Subtype.Subtype etc.        (Remove the spaces from the Type name) 
#                  Document.StandardsDocuments.ISO9000  (where the Type Name was 'Standards Documents')
# <activity> = CREATE_DOCUMENT
# <action>   = CLASSIFY##########################################################################
#
# File: clientSidePluginManagerMappings.properties
#
# This file is used to map specific specific Client Side Plugin JSPs    
# to the generation of specific Flextype pages. 
# No user customizations should be made to this file. If a user, Administrator, 
#  Developer etc. needs to create settings to apply to their local environment, 
# then copy this file and renamed it to custom.clientSidePluginManagerMappings.properties
# and it should be in your /codebase/com/lcs/wc/client/web directory.
# 
# The format is <FlextypePath>.<activity>.<action>.<clientSidePluginType>=<file Path>
# <FlextypePath> = RootType.Subtype.Subtype etc.        (Remove the spaces from the Type name) 
#                  Document.StandardsDocuments.ISO9000  (where the Type Name was 'Standards Documents')
# <activity> = CREATE_DOCUMENT
# <action>   = CLASSIFY
# <clientSidePluginType> = handleWidgetEvent, handleSubmitEvent, or onLoadEvent
# The entry would appear as follows:
#   Document.StandardsDocuments.ISO9000.CREATE_DOCUMENT.CLASSIFY.handleWidgetEvent=/Company/jsp/document/widgetDocumentPlugin_CSP.jsp
############################################################################
## Example settings for the Document FlexType
##Document.StandardsDocuments.ISO9000.CREATE_DOCUMENT.CLASSIFY.handleWidgetEvent=/jsp/document/widgetDocumentStdIso9000_CSP.jsp
##Document.StandardsDocuments.ISO9000.CREATE_DOCUMENT.CLASSIFY.handleSubmitEvent=/jsp/document/submitDocumentStdIso9000_CSP.jsp
##Document.StandardsDocuments.ISO9000.CREATE_DOCUMENT.CLASSIFY.onLoadEvent=/jsp/document/onLoadDocumentStdIso9000_CSP.jsp
#
############################################################################
## Fit Sample initialization of Comments per Last Fit Test Sample value
############################################################################
Sample.CREATE_SAMPLE.CLASSIFY.initPage=/jsp/samples/onLoadInitSampleComments_CSP.jsp
Sample.CREATE_TESTING_REQUEST.CLASSIFY.initPage=/jsp/samples/onLoadInitSampleComments_CSP.jsp
Sample.CREATE_MULTIPLE_SAMPLE.CLASSIFY.initPage=/jsp/samples/onLoadInitSampleComments_CSP.jsp

Product.UPDATE_PRODUCT.INIT.onLoadEvent=/sparc/jsp/product/SPARCProduct_CSP.jsp
Product.UPDATE_SKU.INIT.onLoadEvent=/sparc/jsp/product/SPARCSKU_CSP.jsp
Product.UPDATE_SEASON_PRODUCT_LINK.INIT.onLoadEvent=/sparc/jsp/product/SPARCProductSeasonOnLoad_CSP.jsp
Product.UPDATE_SEASON_PRODUCT_LINK.INIT.handleWidgetEvent=/sparc/jsp/product/SPARCSKUSeasonHandleWidget_CSP.jsp
Product.UPDATE_SEASON_PRODUCT_LINK.PSEUDO_CREATE.handleWidgetEvent=/sparc/jsp/product/SPARCCreateSKUSeasonHandleWidget_CSP.jsp

Color.UPDATE_COLOR.INIT.onLoadEvent=/sparc/jsp/color/SPARCColorOnLoad_CSP.jsp
###Cost sheet Inco terms from source####
###Commented out the below entries as per the ask from customer 08/15/2023####
#CostSheet.UPDATE_MULTI_COSTSHEET.INIT.onLoadEvent=/sparc/jsp/sourcing/SPARCCostSheetIncotermsonLoad_CSP.jsp
#CostSheet.CREATE_COSTSHEET.CLASSIFY.onLoadEvent=/sparc/jsp/sourcing/SPARCCreateCostSheetIncoterms_CSP.jsp
#CostSheet.WHATIF_MULTI_COSTSHEET.CLASSIFY.onLoadEvent=/sparc/jsp/sourcing/SPARCCreateCostSheetIncoterms_CSP.jsp



#Plugin entries to populate BOM name on the CostSheet Create and Update pages - start
#Plugin entries to populate Port Of Origin name on the Aero Breakdown and Highlevel CostSheet Create and Update pages - start
CostSheet.scSparc.scApparelBreakdown.CREATE_COSTSHEET.CLASSIFY.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scApparelBreakdown.CREATE_COSTSHEET.SAVE.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scApparelBreakdown.WHATIF_MULTI_COSTSHEET.CLASSIFY.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scApparelBreakdown.UPDATE_MULTI_COSTSHEET.INIT.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scApparelBreakdown.UPDATE_MULTI_COSTSHEET.SAVE.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scApparelBreakdown.COPY_COSTSHEET_TO_ACTIVE.INIT.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.WHATIF_MULTI_COSTSHEET.INIT.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
#Plugin entries to populate BOM name on the CostSheet Create and Update pages - end

CostSheet.scSparc.scApparelHighLevel.CREATE_COSTSHEET.CLASSIFY.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scApparelHighLevel.CREATE_COSTSHEET.SAVE.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scApparelHighLevel.WHATIF_MULTI_COSTSHEET.CLASSIFY.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scApparelHighLevel.UPDATE_MULTI_COSTSHEET.INIT.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scApparelHighLevel.UPDATE_MULTI_COSTSHEET.SAVE.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scApparelHighLevel.COPY_COSTSHEET_TO_ACTIVE.INIT.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
#Plugin entries to populate Port Of Origin name on the Aero Breakdown and Highlevel CostSheet Create and Update and pages - start


#Plugin entries to populate BOM name on the Footwear CostSheet Create and Update pages - start
CostSheet.scSparc.scFootwearBreakdown.CREATE_COSTSHEET.CLASSIFY.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scFootwearBreakdown.WHATIF_MULTI_COSTSHEET.CLASSIFY.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scFootwearBreakdown.UPDATE_MULTI_COSTSHEET.INIT.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
CostSheet.scSparc.scFootwearBreakdown.COPY_COSTSHEET_TO_ACTIVE.INIT.onLoadEvent=/sparc/jsp/sourcing/SPARCOnLoadCostSheet_CSP.jsp
#Plugin entries to populate BOM name on the Footwear CostSheet Create and Update pages - end