SEASON_CONTROLLER=/sparc/jsp/v2/season/SPARCSeasonController.jsp

#Overriden for derive & update of non calculated attributes ont Costsheet from other sources
SOURCING_CONTROLLER=/sparc/jsp/v2/sourcing/SPARCSourcingController.jsp


#changes for costing uploader
COSTSHEET_UPLOADER_CONTROLLER=/sparc/jsp/sourcing/SPARCCostingUploaderController.jsp

SEASON_PRODUCT_CONTROLLER=/sparc/jsp/v2/season/SPARCSeasonProductController.jsp

#For Side menu explicitly for OOTB Load file
LOAD_CSV_CONTROLLER=/sparc/jsp/load/SPARCCsvLoadFileController.jsp
