#### Add Section totaling in BOM
VIEW_PRODUCT_BOM_DETAILS=/sparc/jsp/v2/flexbom/SPARCViewBOM.jsp
###hide component OOTB Att##
VIEW_BOM_COLUMN_ORDER=/sparc/jsp/flexbom/SPARCViewBOMColumnOrder.jsp
EDIT_BOM_PAGE=/sparc/jsp/v2/flexbom/SPARCEditBOMAlt.jsp
##Product chnage report
SEASON_CHANGE_REPORT=/sparc/jsp/season/SPARCSeasonChangeReport.jsp
## REEBOK_LOGO ##
COMPANY_IMAGE=/sparc/images/Galaxy.png

##TECH PACK FILES#####
SPEC_PAGE_SINGLE_SELECTION2=/sparc/jsp/specification/SPARCChooseSingleSpecPage2.jsp
SPEC_PAGE_SELECTION2=/sparc/jsp/specification/SPARCChooseSpecPages2.jsp

## Populate BOM Names as dropdown
WHATIF_MULTI_COSTSHEET_PAGE=/sparc/jsp/v2/sourcing/SPARCWhatIfMultiCostSheet.jsp
COPY_COSTSHEET_PAGE=/sparc/jsp/v2/sourcing/SPARCCopyCostSheet.jsp

## changes for Summary costing uploader
LINEPLAN_HEADER=/sparc/jsp/season/SPARCLinePlanHeader.jsp
UPLOAD_CS_HIGHLEVEL_DATA_PAGE=/sparc/jsp/sourcing/SPARCUploadHighLevelCostSheetData.jsp
UPLOAD_CS_DETAIL_DATA_PAGE=/sparc/jsp/sourcing/SPARCUploadDetailedCostSheetData.jsp

## Arranging Vendor Attributes
FIND_SUPPLIER_RESULTS=/sparc/jsp/supplier/SPARCFindSupplierResults.jsp

## Excel-TechPack MatColor BOM Report
PRODUCT_SPECIFICATION_PDF_GENERATOR2=/sparc/jsp/product/SPARCPDFProductSpecGenerator2.jsp

SIDE_MENU=/sparc/jsp/v2/main/SPARCSideMenu.jsp